import type { Locale } from "./i18nCatalog";

/**
 * `chat.<key>` namespace data (see `i18nUnified.ts`'s `translate()`) —
 * strings for the Chat panel only. Kept separate from `panelI18n.ts`/
 * `uiI18n.ts` because Chat's vocabulary (conversations, attachments, MCP
 * approval, streaming state) doesn't overlap with the other panels; a string
 * that becomes genuinely shared should move to `panelI18n.ts` instead of
 * being duplicated here.
 */
const common = {
  conversations: "Conversations", messages: "messages", conversation: "Conversation", newChat: "New chat", search: "Search conversations", noMatches: "No matching conversations.", newConversation: "New conversation", newConversationTitle: "Start a new conversation", newConversationDescription: "Ask a question, attach an image when a projector is loaded, or adjust the conversation instructions above.", empty: "Empty", delete: "Delete conversation", copy: "Copy", copied: "Copied", chatMessage: "Chat message", offline: "Server offline — select a model and start it", placeholder: "Message (Enter to send, Shift+Enter for newline)", attachDocument: "Attach document", attachImage: "Attach image", stop: "Stop generation", stopping: "Stopping…", send: "Send message", openModels: "Open model library", startServer: "Start server", startingServer: "Starting server…", openDiagnostics: "Open diagnostics", modelReady: "Your model is ready", thinking: "Thinking process", requestFailed: "Request failed", retry: "Retry last message", pendingImages: "Pending image attachments", pendingDocuments: "Pending document attachments", generating: "Generating…", waitingFirstToken: "Waiting for the first token…", emptyConversation: "Empty conversation", loadMcpTools: "Load MCP tools", loadingMcpTools: "Loading MCP tools…", mcpOptional: "MCP tools are optional and off until loaded", mcpApproval: "calls always require approval", approveTool: "Approve once", rejectTool: "Reject", mcpApprovalRequired: "MCP approval required", contextSources: "Context sources", contextWarningLabel: "Context warning", document: "Document", metricsPrompt: "prompt tokens", metricsCompletion: "completion tokens", metricsFirstToken: "first token", metricsTps: "tok/s", metricsLabel: "Response metrics", attachmentReading: "Reading attachment…", attachmentReady: "Attachment ready", attachmentFailed: "Attachment failed", interrupted: "Generation stopped; partial response preserved.", partialFailed: "Generation failed; partial response preserved.", blockedFailedDescription: "Review diagnostics and retry after checking the selected runtime or memory settings.", blockedNoModelDescription: "No GGUF model is selected yet. Choose one from your local model library.", blockedStartingDescription: "Wait for the local server to become ready, then try again.", blockedStoppedDescription: "The local server is currently stopped. Start it to send your first message.", conversationSettings: "Conversation settings", title: "Title", systemPrompt: "System prompt", systemPromptPlaceholder: "Instructions for this conversation", savedLocallyDescription: "Saved locally with this conversation. It is sent as the system message on the next request.", removeAttachment: "Remove attachment", responseReady: "Response complete", deleteTitle: "Delete this conversation?", deleteBody: "“{title}” and its messages are removed from this computer. This cannot be undone.", deleteConfirm: "Delete conversation",
} as const;

export type ChatTextKey = keyof typeof common;
type ChatTextCatalog = Record<ChatTextKey, string>;

export const chatText: Record<Locale, ChatTextCatalog> = {
  en: common,
  ko: { conversations: "대화", messages: "메시지", conversation: "대화", newChat: "새 채팅", search: "대화 검색", noMatches: "일치하는 대화가 없습니다.", newConversation: "새 대화", newConversationTitle: "새 대화를 시작하세요", newConversationDescription: "질문을 입력하거나 이미지를 첨부하거나 위의 대화 지침을 조정하세요.", empty: "비어 있음", delete: "대화 삭제", copy: "복사", copied: "복사됨", chatMessage: "채팅 메시지", offline: "서버 오프라인 — 모델을 선택하고 시작하세요", placeholder: "메시지 (Enter 전송, Shift+Enter 줄바꿈)", attachDocument: "문서 첨부", attachImage: "이미지 첨부", stop: "생성 중지", stopping: "중지 중…", send: "메시지 전송", openModels: "모델 라이브러리 열기", startServer: "서버 시작", startingServer: "서버 시작 중…", openDiagnostics: "진단 열기", modelReady: "모델이 준비되었습니다", thinking: "생각 과정", requestFailed: "요청 실패", retry: "마지막 메시지 재시도", pendingImages: "첨부할 이미지", pendingDocuments: "첨부할 문서", generating: "생성 중…", waitingFirstToken: "첫 토큰 대기 중…", emptyConversation: "빈 대화", loadMcpTools: "MCP 도구 불러오기", loadingMcpTools: "MCP 도구 로딩 중…", mcpOptional: "MCP 도구는 선택 사항이며 불러올 때까지 꺼져 있습니다", mcpApproval: "호출마다 승인이 필요합니다", approveTool: "한 번 승인", rejectTool: "거부", mcpApprovalRequired: "MCP 승인 필요", contextSources: "컨텍스트 출처", contextWarningLabel: "컨텍스트 경고", document: "문서", metricsPrompt: "프롬프트 토큰", metricsCompletion: "완료 토큰", metricsFirstToken: "첫 토큰", metricsTps: "토큰/초", metricsLabel: "응답 지표", attachmentReading: "첨부 파일 읽는 중…", attachmentReady: "첨부 파일 준비 완료", attachmentFailed: "첨부 파일 실패", interrupted: "생성을 중지했으며 부분 응답을 보존했습니다.", partialFailed: "생성에 실패했으며 부분 응답을 보존했습니다.", blockedFailedDescription: "진단 내용을 확인하고 선택한 런타임이나 메모리 설정을 점검한 뒤 다시 시도하세요.", blockedNoModelDescription: "아직 GGUF 모델을 선택하지 않았습니다. 로컬 모델 라이브러리에서 모델을 선택하세요.", blockedStartingDescription: "로컬 서버가 준비될 때까지 기다린 후 다시 시도하세요.", blockedStoppedDescription: "로컬 서버가 중지되어 있습니다. 첫 메시지를 보내려면 서버를 시작하세요.", conversationSettings: "대화 설정", title: "제목", systemPrompt: "시스템 프롬프트", systemPromptPlaceholder: "이 대화에 적용할 지침", savedLocallyDescription: "이 대화에 로컬로 저장되며 다음 요청의 시스템 메시지로 전송됩니다.", removeAttachment: "첨부 제거", responseReady: "응답 완료", deleteTitle: "이 대화를 삭제할까요?", deleteBody: "“{title}”와 그 메시지가 이 컴퓨터에서 제거됩니다. 되돌릴 수 없습니다.", deleteConfirm: "대화 삭제" } ,
  ja: { ...common, conversations: "会話", messages: "メッセージ", conversation: "会話", newChat: "新しいチャット", search: "会話を検索", noMatches: "一致する会話はありません。", newConversation: "新しい会話", newConversationTitle: "新しい会話を始める", newConversationDescription: "質問を入力するか画像を添付するか、上の会話指示を調整してください。", empty: "空", delete: "会話を削除", copy: "コピー", copied: "コピー済み", chatMessage: "チャットメッセージ", offline: "サーバーオフライン — モデルを選択して起動してください", placeholder: "メッセージ（Enterで送信、Shift+Enterで改行）", attachDocument: "文書を添付", attachImage: "画像を添付", stop: "生成を停止", stopping: "停止中…", send: "メッセージを送信", openModels: "モデルライブラリを開く", startServer: "サーバーを起動", startingServer: "サーバーを起動中…", openDiagnostics: "診断を開く", modelReady: "モデルの準備ができました", thinking: "思考プロセス", requestFailed: "リクエストに失敗しました", retry: "最後のメッセージを再試行", pendingImages: "保留中の画像添付", pendingDocuments: "保留中の文書添付", generating: "生成中…", waitingFirstToken: "最初のトークンを待機中…", emptyConversation: "空の会話", loadMcpTools: "MCPツールを読み込む", loadingMcpTools: "MCPツールを読み込み中…", mcpOptional: "MCPツールは任意で、読み込むまで無効です", mcpApproval: "呼び出しごとに承認が必要です", approveTool: "一度だけ承認", rejectTool: "拒否", mcpApprovalRequired: "MCPの承認が必要です", contextSources: "コンテキストの出典", contextWarningLabel: "コンテキスト警告", document: "文書", metricsPrompt: "プロンプトトークン", metricsCompletion: "完了トークン", metricsFirstToken: "最初のトークン", metricsTps: "トークン/秒", metricsLabel: "応答指標", attachmentReading: "添付ファイルを読み込み中…", attachmentReady: "添付ファイルの準備完了", attachmentFailed: "添付ファイルに失敗", interrupted: "生成を停止しました。部分応答は保存されています。", partialFailed: "生成に失敗しました。部分応答は保存されています。", conversationSettings: "会話設定", title: "タイトル", systemPrompt: "システムプロンプト", systemPromptPlaceholder: "この会話の指示", savedLocallyDescription: "この会話にローカル保存され、次のリクエストのシステムメッセージとして送信されます。", removeAttachment: "添付を削除", responseReady: "応答完了", deleteTitle: "この会話を削除しますか？", deleteBody: "「{title}」とそのメッセージがこのコンピューターから削除されます。元に戻せません。", deleteConfirm: "会話を削除" },
  zh: { conversations: "对话", messages: "条消息", conversation: "对话", newChat: "新聊天", search: "搜索对话", noMatches: "没有匹配的对话。", newConversation: "新对话", newConversationTitle: "开始新对话", newConversationDescription: "提出问题、附加图片或调整上方的对话说明。", empty: "空", delete: "删除对话", copy: "复制", copied: "已复制", chatMessage: "聊天消息", offline: "服务器离线 — 请选择模型并启动服务器", placeholder: "消息（Enter 发送，Shift+Enter 换行）", attachDocument: "附加文档", attachImage: "附加图片", stop: "停止生成", stopping: "正在停止…", send: "发送消息", openModels: "打开模型库", startServer: "启动服务器", startingServer: "正在启动服务器…", openDiagnostics: "打开诊断", modelReady: "模型已准备就绪", thinking: "思考过程", requestFailed: "请求失败", retry: "重试上一条消息", pendingImages: "待处理图片附件", pendingDocuments: "待处理文档附件", generating: "正在生成…", waitingFirstToken: "等待第一个令牌…", emptyConversation: "空对话", loadMcpTools: "加载 MCP 工具", loadingMcpTools: "正在加载 MCP 工具…", mcpOptional: "MCP 工具为可选项，加载前处于关闭状态", mcpApproval: "每次调用都需要批准", approveTool: "批准一次", rejectTool: "拒绝", mcpApprovalRequired: "需要 MCP 批准", contextSources: "上下文来源", contextWarningLabel: "上下文警告", document: "文档", metricsPrompt: "提示词令牌", metricsCompletion: "完成令牌", metricsFirstToken: "首个令牌", metricsTps: "令牌/秒", metricsLabel: "响应指标", attachmentReading: "正在读取附件…", attachmentReady: "附件已准备好", attachmentFailed: "附件失败", interrupted: "生成已停止，部分响应已保留。", partialFailed: "生成失败，部分响应已保留。", blockedFailedDescription: "请查看诊断信息，检查所选运行时或内存设置后重试。", blockedNoModelDescription: "尚未选择 GGUF 模型。请从本地模型库中选择一个模型。", blockedStartingDescription: "请等待本地服务器准备就绪后重试。", blockedStoppedDescription: "本地服务器当前已停止。请启动服务器后发送第一条消息。", conversationSettings: "对话设置", title: "标题", systemPrompt: "系统提示词", systemPromptPlaceholder: "此对话的说明", savedLocallyDescription: "已保存在此对话中，并将在下一次请求中作为系统消息发送。", removeAttachment: "移除附件", responseReady: "响应完成", deleteTitle: "要删除此对话吗？", deleteBody: "“{title}”及其消息将从这台电脑上删除，且无法恢复。", deleteConfirm: "删除对话" },
};

export function assertChatCatalogComplete(): void {
  for (const locale of ["en", "ko", "ja", "zh"] as const) {
    for (const key of Object.keys(common) as ChatTextKey[]) {
      if (!chatText[locale][key]) throw new Error(`Missing chat translation: ${locale}.${key}`);
    }
  }
}

assertChatCatalogComplete();
