import type { Locale } from "./i18nCatalog";

/**
 * `panel.<key>` namespace data (see `i18nUnified.ts`'s `translate()`) —
 * strings shared across Models, Runtimes, Projects, Discover, MCP, Developer
 * and Bench (common actions, empty states, save/scan flows). Panel-specific
 * supplementary strings that don't fit here live in `extraI18n.ts` (`extra.`)
 * instead; Chat's own strings live in `chatI18n.ts` (`chat.`).
 */
const en = {
  models: "Models", modelsDirectory: "Models directory", activeModel: "Active model", noneSelected: "none selected", saveFolder: "Save folder", rescan: "Rescan", scanning: "Scanning…", cancelScan: "Cancel scan", modelsSaved: "Models directory saved.", modelsChanged: "Models directory changed — save it before scanning.", configuredServers: "Configured servers", newItem: "New", noMcpServers: "No MCP servers configured", loraAdapters: "LoRA adapters", projects: "Projects & Presets", newProject: "New project", importJson: "Import JSON", noProjects: "No projects yet", discover: "Discover", mcpServers: "MCP servers", benchmark: "Run benchmark", benchmarkFailed: "Benchmark failed", runtimeCapabilities: "Runtime capabilities",
  saved: "Saved", save: "Save", update: "Update", apply: "Apply", exportJson: "Export JSON", delete: "Delete", remove: "Remove", browse: "Browse…", retry: "Retry", startServer: "Start server", stopServer: "Stop server", restartServer: "Restart server", serverStarted: "Server started.", saveFailed: "Save failed", startFailed: "Start failed", browseFailed: "Browse failed", copyPath: "Copy path", copied: "Copied", selectionFailed: "Selection failed", copyFailed: "Copy failed", restartSwitchQuestion: "Restart server and switch model?", restartSwitch: "Restart and switch", noModels: "No GGUF models found", chooseFolder: "Choose folder", scanModels: "Scan models", searchModels: "Search models", allModels: "All models", visionModels: "Vision sidecars", modelFilterPlaceholder: "Filter by model name or path", selectFolder: "Select a models folder", savedProject: "Saved project", projectActionFailed: "Project action failed", mcpActionFailed: "MCP action failed", developerActionFailed: "Developer action failed", done: "Done", apiReady: "API ready", apiUnavailable: "API unavailable", ready: "Ready", offline: "Offline", startLocalServer: "Start the local server to enable API clients.", repositoryFiles: "Repository files", noGgufFiles: "No GGUF files were found in this repository.", selectRepository: "Select a repository to inspect its GGUF files and choose a quant.", downloads: "downloads", gated: "gated", destination: "Destination", downloadComplete: "Download complete", cancel: "Cancel", loading: "Loading…", savedWorkspaces: "Saved workspaces", runtimeProfile: "Runtime profile", chatWorkspace: "Chat workspace", saveProject: "Save project", updateProject: "Update project", applyRuntime: "Apply runtime settings", confirmAction: "Confirm action", deleteProject: "Delete project", projectNamePlaceholder: "e.g. Code reviewer", optionalSidecar: "optional sidecar", noModelSelected: "no model selected", iterations: "Iterations", cancelBenchmark: "Cancel benchmark", canceling: "Canceling…", noModelBenchmark: "no model selected", serverRunningBenchmark: "server is running (stop it to benchmark)", benchmarkEmpty: "Run a benchmark to see prompt-processing and token-generation speed.", benchmarkResults: "Benchmark tokens per second results", effectiveArgs: "Effective llama-bench arguments", ariaModelBrowse: "Choose a GGUF model file", ariaGgufModels: "GGUF models", ariaRepositoryFiles: "Repository files", ariaConfiguredServers: "Configured MCP servers", ariaProjectScope: "Project scope summary", ariaDeveloperSummary: "Developer connection summary",
} as const;
export type PanelTextKey = keyof typeof en;
export type PanelTextCatalog = Record<PanelTextKey, string>;

const ko: Partial<Record<PanelTextKey, string>> = {
  models:"모델", modelsDirectory:"모델 디렉터리", activeModel:"활성 모델", noneSelected:"선택되지 않음", saveFolder:"폴더 저장", rescan:"다시 검색", scanning:"검색 중…", cancelScan:"검색 취소", modelsSaved:"모델 디렉터리를 저장했습니다.", modelsChanged:"모델 디렉터리가 변경되었습니다. 검색 전에 저장하세요.", configuredServers:"설정된 서버", newItem:"새로 만들기", noMcpServers:"설정된 MCP 서버가 없습니다", loraAdapters:"LoRA 어댑터", projects:"프로젝트 및 프리셋", newProject:"새 프로젝트", importJson:"JSON 가져오기", noProjects:"아직 프로젝트가 없습니다", discover:"탐색", mcpServers:"MCP 서버", benchmark:"벤치마크 실행", benchmarkFailed:"벤치마크 실패", runtimeCapabilities:"런타임 기능", saved:"저장됨", save:"저장", update:"업데이트", apply:"적용", exportJson:"JSON 내보내기", delete:"삭제", remove:"제거", browse:"찾아보기…", retry:"재시도", startServer:"서버 시작", stopServer:"서버 중지", restartServer:"서버 재시작", serverStarted:"서버를 시작했습니다.", saveFailed:"저장 실패", startFailed:"시작 실패", browseFailed:"찾아보기 실패", copyPath:"경로 복사", copied:"복사됨", noModels:"GGUF 모델이 없습니다", chooseFolder:"폴더 선택", scanModels:"모델 검색", searchModels:"모델 검색", allModels:"모든 모델", visionModels:"비전 사이드카", modelFilterPlaceholder:"모델 이름 또는 경로로 필터링", selectFolder:"모델 폴더를 선택하세요",  savedProject:"프로젝트 저장됨", projectActionFailed:"프로젝트 작업 실패", mcpActionFailed:"MCP 작업 실패", developerActionFailed:"개발자 작업 실패", done:"완료", apiReady:"API 준비됨", apiUnavailable:"API 오프라인", ready:"준비됨", offline:"오프라인", startLocalServer:"API 엔드포인트를 사용하려면 상단에서 로컬 서버를 시작하세요.", repositoryFiles:"저장소 파일", noGgufFiles:"이 저장소에 GGUF 파일이 없습니다.", selectRepository:"저장소를 선택해 GGUF 파일을 확인하고 양자화를 선택하세요.", downloads:"다운로드", gated:"접근 제한", destination:"대상", downloadComplete:"다운로드 완료", cancel:"취소", loading:"로딩 중…", savedWorkspaces:"저장된 작업 공간", runtimeProfile:"런타임 프로필", chatWorkspace:"채팅 작업 공간", saveProject:"프로젝트 저장", updateProject:"프로젝트 업데이트", applyRuntime:"런타임 설정 적용", confirmAction:"작업 확인", deleteProject:"프로젝트 삭제", projectNamePlaceholder:"예: 코드 리뷰어", optionalSidecar:"선택적 사이드카", noModelSelected:"모델이 선택되지 않음", iterations:"반복 횟수", cancelBenchmark:"벤치마크 취소", canceling:"취소 중…", noModelBenchmark:"모델이 선택되지 않음", serverRunningBenchmark:"서버가 실행 중입니다(벤치마크 전에 중지하세요)", benchmarkEmpty:"벤치마크를 실행하면 프롬프트 처리 및 토큰 생성 속도가 표시됩니다.", benchmarkResults:"벤치마크 초당 토큰 결과", effectiveArgs:"실제 llama-bench 인자", ariaModelBrowse:"GGUF 모델 파일 선택", ariaGgufModels:"GGUF 모델", ariaRepositoryFiles:"저장소 파일", ariaConfiguredServers:"설정된 MCP 서버", ariaProjectScope:"프로젝트 범위 요약", ariaDeveloperSummary:"개발자 연결 요약"
};
const ja: Partial<Record<PanelTextKey, string>> = { ...ko, models:"モデル", modelsDirectory:"モデルディレクトリ", activeModel:"アクティブなモデル", rescan:"再スキャン", cancelScan:"スキャンをキャンセル", scanning:"スキャン中…", save:"保存", apply:"適用", delete:"削除", browse:"参照…", startServer:"サーバーを起動", stopServer:"サーバーを停止", projects:"プロジェクトとプリセット", newProject:"新しいプロジェクト", noProjects:"プロジェクトはまだありません", discover:"探索", mcpServers:"MCPサーバー", benchmark:"ベンチマークを実行", repositoryFiles:"リポジトリファイル", noGgufFiles:"このリポジトリにGGUFファイルはありません。", destination:"保存先", cancel:"キャンセル", loading:"読み込み中…", saveProject:"プロジェクトを保存", updateProject:"プロジェクトを更新", applyRuntime:"ランタイム設定を適用", iterations:"反復回数", cancelBenchmark:"ベンチマークをキャンセル", canceling:"キャンセル中…", ariaModelBrowse:"GGUFモデルファイルを選択" };
const zh: Partial<Record<PanelTextKey, string>> = { ...ko, models:"模型", modelsDirectory:"模型目录", activeModel:"当前模型", rescan:"重新扫描", cancelScan:"取消扫描", scanning:"正在扫描…", save:"保存", apply:"应用", delete:"删除", browse:"浏览…", startServer:"启动服务器", stopServer:"停止服务器", projects:"项目和预设", newProject:"新建项目", noProjects:"暂无项目", discover:"发现", mcpServers:"MCP服务器", benchmark:"运行基准测试", repositoryFiles:"仓库文件", noGgufFiles:"此仓库中没有GGUF文件。", destination:"目标位置", cancel:"取消", loading:"正在加载…", saveProject:"保存项目", updateProject:"更新项目", applyRuntime:"应用运行时设置", iterations:"迭代次数", cancelBenchmark:"取消基准测试", canceling:"正在取消…", ariaModelBrowse:"选择GGUF模型文件" };
export const panelText: Record<Locale, PanelTextCatalog> = { en, ko: { ...en, ...ko } as PanelTextCatalog, ja: { ...en, ...ja } as PanelTextCatalog, zh: { ...en, ...zh } as PanelTextCatalog };
export function assertPanelCatalogComplete(): void { for (const locale of ["en", "ko", "ja", "zh"] as const) for (const key of Object.keys(en) as PanelTextKey[]) if (!panelText[locale][key]?.trim()) throw new Error(`Missing panel translation: ${locale}.${key}`); }
assertPanelCatalogComplete();
